#!/usr/bin/python2
# -*- coding: utf-8 -*-

from __future__ import division
from scipy import *
from pylab import *
import sys

def usage():
    print "USAGE : ./106bombyx k (k <= 4 && k >= 1)\n or"
    print "USAGE : ./106bombyx imin imax (0 <= imin < imax)"
    sys.exit()

def func_k(k):
    i = 1
    n = 10
    x = []
    y = []
    x.append(i)
    y.append(n)
    while (i <= 100):
        n = k * n * ((1000 - n) / 1000)
        x.append(i)
        y.append(n)
        i += 1
    plot(x, y)
    xlabel(ur"i", fontsize=20)
    ylabel(ur"X(i)", fontsize=20)

def func_i(imin,imax):
    i = imin
    k = 1
    x = []
    y = []
    while (k <= 4):
        n = 10
        i = imin
        y.append(n)
        x.append(k)
        while (i <= imax):
            n = k * n * ((1000 - n) / 1000)
            x.append(k)
            y.append(n)
            i += 1
        k += 0.01
    plot(x, y, ':')
    xlabel(ur"k", fontsize=20)
    ylabel(ur"X(i)", fontsize=20)

if (len(sys.argv) < 2 or len(sys.argv) > 3):
    usage()

if (len(sys.argv) == 2):
    k = float(sys.argv[1])
    if (k < 1 or k > 4):
        print "ERROR : 1 <= k <= 4"
        usage()
    func_k(float(k))
elif (len(sys.argv) == 3):
    imin = sys.argv[1]
    if (imin < 0):
        print "ERROR : imin < 0"
    imax = sys.argv[2]
    if (imax < imin):
        print "ERROR : imin > imax"
    func_i(float(imin), float(imax))

fig = gcf()
fig.canvas.set_window_title('PAPILLOOOOOOOOOONNNNNNNNNNNNNNN')
title(u"Bombyx", fontsize=16)
show()
