#!/usr/bin/python2
# -*- coding: utf-8 -*-

from __future__ import division
from scipy import *
from pylab import *
import sys

def usage():
    print "USAGE : ./106bombyx k (k <= 4 && k >= 1)\n or"
    print "USAGE : ./106bombyx imin imax (0 <= imin < imax)"
    sys.exit()

def func_k(k):
    i = 1
    n = 10
    x = []
    y = []
    x.append(i)
    y.append(n)
    while (i <= 100):
        n = k * n * ((1000 - n) / 1000)
        x.append(i)
        y.append(n)
        i += 1
    plot(x, y)
    xlabel(ur"$i$", fontsize=20)
    ylabel(ur"$x_{i}$", fontsize=20)

def get_value(size, k):
    n = 10
    i = 1
    x = []
    x.append(n)
    while (i < size):
        n = k * n * ((1000 - n) / 1000)
        x.append(n)
        i += 1
    return (x)

def func_i(imin,imax):
    x = []
    y = []
    k = 1
    while (k <= 4):
        values = get_value(imax, k)
        y += values[imin - 1:]
        for i in range (imax - imin + 1):
            x.append(k)
        k += 0.01
    plot(x, y, color = 'blue', lw=2, ls='*', marker='o', markersize=1, markerfacecolor="blue", markeredgecolor="blue")
    xlabel(ur"$k$", fontsize=20)
    ylabel(ur"$x_{i}$", fontsize=20)

if (len(sys.argv) < 2 or len(sys.argv) > 3):
    usage()

if (len(sys.argv) == 2):
    try:
        k = float(sys.argv[1])
    except:
        print "Please enter a number"
        usage()
    if (k < 1 or k > 4):
        print "ERROR : 1 <= k <= 4"
        usage()
    func_k(float(k))
elif (len(sys.argv) == 3):
    try:
        imin = int(sys.argv[1])
    except:
        print "Please enter a number"
        usage()
    if (imin < 0):
        print "ERROR : imin < 0"
        usage()
    try:
        imax = int(sys.argv[2])
    except:
        print "Please enter a number"
        usage()
    if (imax < imin):
        print "ERROR : imin > imax"
        usage()
    func_i(int(imin), int(imax))

fig = gcf()
fig.canvas.set_window_title('PAPILLOOOOOOOOOONNNNNNNNNNNNNNN')
title(u"Bombyx", fontsize=16)
show()
